#!/bin/bash
function tmux_attach() {
    if [ "$TERM" != "nuclide" ] && [ -t 0 ] && [ -z "$TMUX" ] && which tmux >/dev/null 2>&1; then
        if tmux has-session -t auto >/dev/null 2>&1; then
            tmux -2CC attach-session -t auto
        else
            tmux -2CC new-session -s auto
        fi
    fi
}
