#!/bin/bash
#GNU vs BSD top command line arguments
# Delay updates by 10 sec and sort by CPU
(man top 2>&1 | grep Linux> /dev/null)
if [ $? -eq 0 ]; then
  echo '-c -d10'
else
  echo '-s10 -ocpu'
fi;
